version: "3.3"

volumes:
  caddy_data:
  caddy_config:

services:
  # Optional Caddy reverse-proxy for local HTTPS termination (SearxNG only)
  caddy-tls:
    image: caddy:2.8-alpine@sha256:af32e97399febea808609119bb21544d0265c58a02836576e32a2d082c262c17
    networks:
      - goresearch_net
    volumes:
      - ./devops/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "sh", "-c", "caddy validate --config /etc/caddy/Caddyfile"]
    restart: unless-stopped
    profiles: ["tls"]
    depends_on:
      searxng:
        condition: service_healthy
