name: goresearch

networks:
  goresearch_net:
    driver: bridge
    internal: true

volumes:
  http_cache:
  llm_cache:
  reports:

services:
  # One-shot init to align ownership of named volumes with APP_UID:APP_GID
  perms-init:
    image: alpine:3.20@sha256:b3119ef930faabb6b7b976780c0c7a9c1aa24d0c75e9179ac10e6bc9ac080d0d
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    command: ["sh", "-lc", "chown -R ${APP_UID:-1000}:${APP_GID:-1000} /app/.goresearch-cache /app/reports || true"]
    volumes:
      - http_cache:/app/.goresearch-cache/http
      - llm_cache:/app/.goresearch-cache/llm
      - reports:/app/reports
    networks:
      - goresearch_net
    restart: "no"
    profiles: ["dev", "test", "offline", "tls"]

  
  research-tool:
    # Runs the CLI from source using the official Go image.
    # A dedicated Dockerfile will be added in a later checklist item.
    image: golang:1.24-bookworm@sha256:2679c15c940573aded505b2f2fbbd4e718b5172327aae3ab9f43a10a5c700dfc
    working_dir: /app
    volumes:
      - ./:/app
      - http_cache:/app/.goresearch-cache/http
      - llm_cache:/app/.goresearch-cache/llm
      - ./reports:/app/reports
    # Load environment from .env (Compose default) and avoid in-file secrets.
    environment:
      - LLM_BASE_URL=${LLM_BASE_URL:-http://host.docker.internal:1234/v1}
      - LLM_MODEL=${LLM_MODEL:-openai/gpt-oss-20b}
      # Note: LLM_API_KEY must be provided via environment/.env and is
      # intentionally not defaulted here to avoid baking secrets.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Run as the invoking host user's UID:GID to avoid permission issues on bind mounts
    command: ["sleep", "infinity"]
    networks:
      - goresearch_net
    profiles: ["dev"]
    depends_on:
      perms-init:
        condition: service_completed_successfully

  # Optional services (LLM, search, TLS, test helpers) are moved to
  # docker-compose.optional.yml to keep the base stack minimal for the nginx
  # use case. See that file for additional profiles and services.
